"""empty message

Revision ID: 1a718932a6fc
Revises: ac5a8560f1fd
Create Date: 2020-11-22 22:16:28.333757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a718932a6fc'
down_revision = 'ac5a8560f1fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tour', sa.Column('name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tour', 'name')
    # ### end Alembic commands ###
