"""empty message

Revision ID: 27b5a273a861
Revises: 89dfdbf2d3b9
Create Date: 2020-11-26 10:48:15.940697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27b5a273a861'
down_revision = '89dfdbf2d3b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('email', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'email')
    # ### end Alembic commands ###
