"""empty message

Revision ID: 6bae619ac9f6
Revises: 27b5a273a861
Create Date: 2020-11-26 17:27:31.801212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bae619ac9f6'
down_revision = '27b5a273a861'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('tour_date', sa.Date(), nullable=True))
    op.create_index(op.f('ix_order_tour_date'), 'order', ['tour_date'], unique=False)
    op.drop_index('ix_order_add_date', table_name='order')
    op.drop_column('order', 'add_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('add_date', sa.DATE(), autoincrement=False, nullable=True))
    op.create_index('ix_order_add_date', 'order', ['add_date'], unique=False)
    op.drop_index(op.f('ix_order_tour_date'), table_name='order')
    op.drop_column('order', 'tour_date')
    # ### end Alembic commands ###
