"""empty message

Revision ID: ac5a8560f1fd
Revises: 
Create Date: 2020-11-21 07:18:08.906943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac5a8560f1fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('passport', sa.String(length=15), nullable=False),
    sa.Column('first_name', sa.String(length=99), nullable=True),
    sa.Column('last_name', sa.String(length=99), nullable=True),
    sa.Column('registration_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('passport')
    )
    op.create_table('tour',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=63), nullable=True),
    sa.Column('hotel', sa.String(length=127), nullable=True),
    sa.Column('tour_includes', sa.String(length=255), nullable=True),
    sa.Column('day_cost', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tour_id', sa.Integer(), nullable=True),
    sa.Column('client_pass', sa.String(length=80), nullable=True),
    sa.Column('add_date', sa.Date(), nullable=True),
    sa.Column('days', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_pass'], ['client.passport'], ),
    sa.ForeignKeyConstraint(['tour_id'], ['tour.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_add_date'), 'order', ['add_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_add_date'), table_name='order')
    op.drop_table('order')
    op.drop_table('tour')
    op.drop_table('client')
    # ### end Alembic commands ###
